### ISSUE TITLE
infografia 

### ISSUE THREAD

**Issue by Alberto796** [SistemasTecTlaxiaco/infografia-Alberto796#2]
[Uploading genially-64f15f5231b94f00180e2d25 (3).pdf…]()
[Doc1.docx](https://github.com/SistemasTecTlaxiaco/infografia-Alberto796/files/12554976/Doc1.docx)
![001_00](https://github.com/SistemasTecTlaxiaco/infografia-Alberto796/assets/143294848/366a8e75-4a8a-4725-b602-9b37b0beb12c)

**Comment by 00Asaf00** [comment]
Redacción y Ortografía: 100%
Exposición de Ideas centrales: 75%
Organización de la Información: 75%
Uso de imágenes y colores: 50%
Presentación Visual: 50%
Referencias: 75%
Presentación: 70%

Calificación: 0.2 * 70 = 14

**Comment by josealfredo79** [comment]
Revisado...
